### ISSUE TITLE
Publicar uma área de datas importantes no site

### ISSUE THREAD

**Issue by nbluis** [pgbr/www-2015#11]
Deve conter.
- 05/05/2015 - Abertura Chamada de Trabalhos
- 31/06/2015 - Encerramento Chamada de Trabalhos
- 15/07/2015 - Notificação autores trabalhos aceitos
- 15/08/2015 - Publicação Grade Oficial

**Comment by nbluis** [comment]
Exemplo.
http://pgbr.postgresql.org.br/2013/datas.php

**Comment by fabriziomello** [comment]
Pessoal, onde estamos com isso?? De acordo com o que coloquei ali a abertura de chamada de trabalhos é amanhã 05/05/2015
