### ISSUE TITLE
Adicionar logo DBSeller nos patrocinadores "Ouro"

### ISSUE THREAD

**Issue by fabriziomello** [pgbr/www-2015#14]
Adicionar logo DBSeller com link para o site (http://www.dbseller.com.br) nos patrocinadores "Ouro". 

Imagem: http://pgbr.postgresql.org.br/2013/imgs/dbseller.jpg

Lembrem-se de observar as regras de "tamanho dos logos" conforme nosso plano de patrocinio em:

http://pgbr.postgresql.org.br/2015/docs/plano_captacao.pdf

**Comment by nbluis** [comment]
Legal.

Os tamanhos dos logos já estão implementados direitinho, basta adicionar no
docpad.coffe que ele redimensiona corretamente.

Se ninguém puxar coloco agora a noite.
Em 16/07/2015 16:30, "Fabrízio de Royes Mello" notifications@github.com
escreveu:
