### ISSUE TITLE
Adicionar logo "PostgreSQL Professional" aos patrocinadores "Ouro"

### ISSUE THREAD

**Issue by fabriziomello** [pgbr/www-2015#15]
Adicionar logo "PostgreSQL Professional" aos patrocinadores "Ouro" conforme email enviado. O link para o site da empresa é:

http://postgrespro.ru/

Vou verificar com eles se tem uma versão em ingles do site e mando noticias.

**Comment by centeno** [comment]
![pgpro-logo-01](https://cloud.githubusercontent.com/assets/571016/9094359/bc8cc164-3b87-11e5-94e6-142c2497e8b1.png)
