### ISSUE TITLE
Adicionar Palestrante Confirmado: "Álvaro Herrera"

### ISSUE THREAD

**Issue by fabriziomello** [pgbr/www-2015#17]
Nome: Álvaro Herrera
Origem: Chile
Mini-bio: Álvaro started writing code for PostgreSQL in 2002 and hasn't stopped since, having contributed features and bug fixes for every release since 7.2: shared row locking, the autovacuum daemon, background workers, BRIN indexes, and many more. He's currently a PostgreSQL Committer and Major Developer working for 2ndQuadrant, a world-wide PostgreSQL services organization.

**Comment by nbluis** [comment]
@fabriziomello se tiver uma fotinho seria legal.

**Comment by sebawebber** [comment]
https://www.pgcon.org/2012/schedule/images/person-243-128x128.png

**Comment by sebawebber** [comment]
ou talvez essa @nbluis :
https://www.flickr.com/photos/fcatrin/880741203/

**Comment by fabriziomello** [comment]
Tem que ser mais atual. Vou ver com ele.

Em sexta-feira, 14 de agosto de 2015, Sebastian Webber <
notifications@github.com> escreveu:

> ou talvez essa @nbluis https://github.com/nbluis :
> https://www.flickr.com/photos/fcatrin/880741203/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pgbr/www-2015/issues/17#issuecomment-131215610.

## 

Fabrízio de Royes Mello
Consultoria/Coaching PostgreSQL

> > Timbira: http://www.timbira.com.br
> > Blog: http://fabriziomello.github.io
> > Linkedin: http://br.linkedin.com/in/fabriziomello
> > Twitter: http://twitter.com/fabriziomello
> > Github: http://github.com/fabriziomello

**Comment by fabriziomello** [comment]
@nbluis @sebastianwebber ele pediu para "recortar" dessa https://www.flickr.com/photos/alvherre/20369901900/in/dateposted-public/

**Comment by nbluis** [comment]
![alvaro](https://cloud.githubusercontent.com/assets/24320/9342921/fc76a7f2-45d4-11e5-838a-10abf8bff080.png)

**Comment by fabriziomello** [comment]
Perfeito

Em terça-feira, 18 de agosto de 2015, Eduardo Bohrer <
notifications@github.com> escreveu:

> [image: alvaro]
> https://cloud.githubusercontent.com/assets/24320/9342921/fc76a7f2-45d4-11e5-838a-10abf8bff080.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pgbr/www-2015/issues/17#issuecomment-132353905.

## 

Fabrízio de Royes Mello
Consultoria/Coaching PostgreSQL

> > Timbira: http://www.timbira.com.br
> > Blog: http://fabriziomello.github.io
> > Linkedin: http://br.linkedin.com/in/fabriziomello
> > Twitter: http://twitter.com/fabriziomello
> > Github: http://github.com/fabriziomello
