### ISSUE TITLE
Adicionar mídias sociais e e-mail de contato ao site

### ISSUE THREAD

**Issue by nbluis** [pgbr/www-2015#2]
https://twitter.com/postgresqlbr
http://www.linkedin.com/groups?mostPopular=&gid=2748187
- Facebook: @fabriziomello sabe me dizer se o facebook da comunidade/evento já existe ?

**Comment by fabriziomello** [comment]
Aguardando o retorno do Fernando Bueno com os links das mídias sociais.

**Comment by nbluis** [comment]
Adicionar e-mail de contato também. pgbr@postgresql.org.br

**Comment by fabriziomello** [comment]
Midias sociais:
Facebook: https://www.facebook.com/pgbr2015
Twitter: @postgresqlbr
