### ISSUE TITLE
Adicionar Palestrantes Confirmados

### ISSUE THREAD

**Issue by fabriziomello** [pgbr/www-2015#28]
Adicionar demais palestrantes confirmados de acordo com o documento (planilha "contato palestrantes"): https://docs.google.com/spreadsheets/d/1dZYBg_qBYCgj2dgLMZRDgEoBfwfpALYFWwgpzhPK_9g/edit#gid=247694709

**Comment by guedes** [comment]
Apenas linkando diretamente para a planilha "Contato palestrante") o link seria https://docs.google.com/spreadsheets/d/1dZYBg_qBYCgj2dgLMZRDgEoBfwfpALYFWwgpzhPK_9g/edit#gid=1500629401

**Comment by fabriziomello** [comment]
@nbluis @gelias Pessoal, temos prioridade nessa issue... e penso que precisamos colocar também qual a palestra que será ministrada, porque as pessoas irão ao nosso site para se inscrever mas querem saber o conteúdo do evento, ou seja, palestras e palestrantes.

**Comment by nbluis** [comment]
Vou tentar tocar algo hoje, mas o tempo essa semana ta bem esgotado.

**Comment by gelias** [comment]
Tentarei dar uma olhada quando chegar em casa hoje, pois o resto da semana
ta punk com o TDC.

Em qua, 23 de set de 2015 às 17:48, Eduardo Bohrer notifications@github.com
escreveu:

**Comment by nbluis** [comment]
Agora o titulo das talks aparecem junto aos palestrantes.
Agora basta adicionar os demais palestrantes e talks no docpad.coffe.

**Comment by fabriziomello** [comment]
Aqui tem informação da palestra do Álvaro Herrera:
http://pgday.ru/en/papers/22

**Comment by fabriziomello** [comment]
Pessoal, precisamos fechar essa Issue... o Rafael Helm está aguardando para poder lançar a série de divulgações do evento

**Comment by gelias** [comment]
Fiquei de olhar isso ontem, porém não consegui!
Hoje final da tarde irei trabalhar nela!

Em ter, 29 de set de 2015 às 13:31, Fabrízio de Royes Mello <
notifications@github.com> escreveu:

**Comment by sebawebber** [comment]
a descrição da palestra do Luis Fernando Bueno está errada. =/

2015-10-01 0:51 GMT-03:00 Guilherme Elias notifications@github.com:

> Closed #28 https://github.com/pgbr/www-2015/issues/28 via 332517d
> https://github.com/pgbr/www-2015/commit/332517d98398ddecfc05e7b9611478021366b7c3
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pgbr/www-2015/issues/28#event-423825903.

## 

Sebastian Webber
http://swebber.me

**Comment by nbluis** [comment]
@sebastianwebber conferi na planilha e parece estar ok.

**Comment by sebawebber** [comment]
@nbluis, dá uma olhada na foto abaixo:

![erro](https://cloud.githubusercontent.com/assets/2515929/10255703/7c4a6eda-6922-11e5-9934-9d7fb8f7b84d.png)

Apenas pro Luis Fernando Bueno tem um-mini curriculo embaixo do titulo da
palestra.

Todos tem que ter o mini curriculo ou todos tem que mostrar a descrição da
palestra?

**Comment by fabriziomello** [comment]
Palestra

**Comment by nbluis** [comment]
@sebastianwebber vamos ter que revisar.
Na pratica deveria ser minibio em todos e o título da palestra.

A descrição da palestra deveria estar em outro lugar.

**Comment by fabriziomello** [comment]
@nbluis isso ficará assim na grade... nessa divulgação inicial precisamos do conteúdo por conta da divulgação que a wildtech está fazendo pra nós... blz?

**Comment by fabriziomello** [comment]
Essa issue já não está concluida??

**Comment by guedes** [comment]
A grade vai continuar como uma lista ou vai ser uma grade em forma de tabela? Pareceu um pouco confuso os horários repetidos já que não aparece informação de sala.

**Comment by nbluis** [comment]
Vou dar uma trabalhada nisso na sequência.

**Comment by nbluis** [comment]
Dêem uma olhada agora @guedes @fabriziomello @centeno 
http://pgbr.github.io/www-2015/#schedule

**Comment by nbluis** [comment]
Alem disso, seria legal ter as minibios dos outros palestrantes para adicioarmos na área de palestrantes.

**Comment by centeno** [comment]
Ficou afu!

Porém, particularmente, acho que as informações dos palestrantes(foto, bio,
links, etc) deveriam constar na grade... Assim eliminamos a sessão
"Palestrantes"

Att,

## Centeno,  D.

Technical leader at Intermídia
Consulting at Forehead
Mobile: (51) 9371.8871
Website: www.diegocenteno.com

2015-10-19 14:27 GMT-02:00 Eduardo Bohrer notifications@github.com:

**Comment by sebawebber** [comment]
> Porém, particularmente, acho que as informações dos palestrantes(foto, bio,
> links, etc) deveriam constar na grade... Assim eliminamos a sessão
> "Palestrantes"

+1

**Comment by nbluis** [comment]
Não sei se hoje, mas vou tentar fazer um protótipo disso. Baby steps. vamos agora rechear a grade com o que temos, que acho que falta coisa ali não ?

**Comment by sebawebber** [comment]
Vou abrir um novo issue pra grade. Vou tentar te ajudar @nbluis !
