### ISSUE TITLE
Criar grade de palestras

### ISSUE THREAD

**Issue by nbluis** [pgbr/www-2015#3]
Podemos tirar uma base pela grade padrão do confboilerplate

Porém deve suportar:
- 3 trilhas durante em paralelo durante 3 dias
- Ser responsiva

**Comment by fabriziomello** [comment]
Como estamos nessa issue?

**Comment by nbluis** [comment]
Vou voltar a trabalhar nisso assim que terminar a parte de contatos.

**Comment by fabriziomello** [comment]
O email para contato é pgbr@postgresql.org.br (confirmei isso com o Fike já)

**Comment by fabriziomello** [comment]
Pessoal, precisamos agilizar essa parte... dia 10/10/2015 está previsto a publicação da grade oficial

**Comment by gelias** [comment]
Reabrindo para ajustes necessários ainda ...
