### ISSUE TITLE
Alterar dados de Contato

### ISSUE THREAD

**Issue by fabriziomello** [pgbr/www-2015#35]
Precisamos alterar os dados de contato do site para:

Espaço de Projetos
Telefone: (51) 3028.9398 / 3907.9398
Celular: (51) 9388-2236
Horário: 9:30 às 12:00 e das 14:00 às 17:00
E-mail: eventos@espacodeprojetos.com.br

Isso porque esse ano como todos sabem essa empresa está como nossa parceira e nos auxiliando em toda parte operacional do evento.

**Comment by sebawebber** [comment]
@fabriziomello,
troco toda a sessão de contato, vide abaixo, pelo texto acima? Mantenho os botões das redes sociais?

![screen shot 2015-10-19 at 20 51 09](https://cloud.githubusercontent.com/assets/2515929/10593520/3c1c7bda-76a3-11e5-917a-ba2933ee8aae.png)

**Comment by sebawebber** [comment]
Valeu pela ajuda @gelias !
