### ISSUE TITLE
Implementar grade de palestras

### ISSUE THREAD

**Issue by sebastianwebber** [pgbr/www-2015#37]
Discussão iniciado no issue #28 .

Tocar daqui.

**Comment by sebawebber** [comment]
@nbluis,

Achei uma referencia beeeeem legal:
- [http://codepen.io/geoffyuen/pen/FCBEg](http://codepen.io/geoffyuen/pen/FCBEg)

**Comment by sebawebber** [comment]
Iniciei um prototipo em: http://codepen.io/sebastianwebber/pen/MaQWxw
