### ISSUE TITLE
Adicionar logo "Dextra" aos patrocinadores Bronze

### ISSUE THREAD

**Issue by fabriziomello** [pgbr/www-2015#38]
Adicionar logo "Dextra" aos patrocinadores Bronze.

https://dl.dropboxusercontent.com/u/4342654/dextra_logo_2013_RGB_800pxw.jpg

**Comment by sebawebber** [comment]
Vou dar uma olhada.

**Comment by fabriziomello** [comment]
@sebastianwebber conhece o lema do Mestre Yoda???

**Comment by sebawebber** [comment]
vai lá @fabriziomello conta aí!

O logo deles ficou pequeno.. deixo assim mesmo? Olha aí
![screen shot 2015-10-21 at 17 57 35](https://cloud.githubusercontent.com/assets/2515929/10648464/454ab264-781d-11e5-9af0-5513089eaeeb.png)

**Comment by sebawebber** [comment]
@fabriziomello no plano de captação, a proporção é:

| Tipo | Medida |
| --- | --- |
| bronze | ½u |
| silver | ⅔u |
| golde | ¾u |
| platina | 1u |

Talvez a imagem esteja adequada, o que tu acha?

**Comment by fabriziomello** [comment]
Então, ela tem metade do tamanho do logo da uniritter?

**Comment by sebawebber** [comment]
@fabriziomello ,

seguindo a regra que citei acima, deixei as configurações dos logos dessa forma:

|  | 1u | ¾u | ⅔u | ½u |
| --- | --- | --- | --- | --- |
| **Altura máxima** | 150px | 115px | 100px | 75px |
| **Tamanho** | 80% | 60% | 53% | 40% |

Ajustei também o apoio para ficar ainda menor que o patrocinador bronze:

| Altura máxima | tamanho |
| --- | --- |
| 30px | 15% |
