### ISSUE TITLE
Broken layout on Firefox

### ISSUE THREAD

**Issue by centeno** [pgbr/www-2015#4]

**Comment by nbluis** [comment]
The only bug I found was in the sponsors section, the image is too big. That's right? 
I'll fix this now.

**Comment by fabriziomello** [comment]
Where are we on this?

**Comment by nbluis** [comment]
@centeno  ?

**Comment by centeno** [comment]
Logo tipo da Uniritter voltou a ficar "gigante" quebrando o layout

**Comment by nbluis** [comment]
@centeno dá uma olhada agora.

**Comment by centeno** [comment]
Feito @nbluis !
