### ISSUE TITLE
Adicionar logo "Tecnisys" aos patrocinadores OURO

### ISSUE THREAD

**Issue by fabriziomello** [pgbr/www-2015#44]
Adicionar logo "Tecnisys" aos patrocinadores OURO

Url:
http://www.tecnisys.com.br

Logo:
https://dl.dropboxusercontent.com/u/4342654/Logo%20Tecnisys%20JPEG.jpg

**Comment by sebawebber** [comment]
@fabriziomello removo a referencia da tecnisys no logo da enterprisedb?
