### ISSUE TITLE
Alterar Palestrante Desistente

### ISSUE THREAD

**Issue by fabriziomello** [pgbr/www-2015#48]
Precisamos remover o palestrante: "Miguel Di Ciurcio Filho" e palestra "Administrando servidores PostgreSQL com Puppet" (Palestrantes e Agenda) e colocaremos:

Palestrante: Fábio Telles Rodrigues
Palestra: Oracle X PostgreSQL
Resumo: Semelhanças, vantagens e disvantagens entre ambos SGDBs
Descricao: Uma comparação franca e bem humorada sobre as diferenças e semelhanças entre o PostgreSQL e o Oracle.

**Comment by sebawebber** [comment]
@fabriziomello vou apenas trocar os dados da palestra e palestrante e deixar o mesmo horário e local.
