### ISSUE TITLE
Revisar a responsividade do site

### ISSUE THREAD

**Issue by nbluis** [pgbr/www-2015#5]
Revisão geral.

Pelo que ví por enquanto, o logo quebra em telas pequenas.

**Comment by centeno** [comment]
Vou tentar revisar tudo isso no feriado

**Comment by nbluis** [comment]
Na prática o problema é que o logo é uma palavra com fonte aumentada.
Porém isso precisa ser progressivo de acordo com o tamanho da tela.
Percentagem não pode ser usada para fontes, então precisamos pensar uma maneira mais inteligente de resolver isso.
