### ISSUE TITLE
URGENTE! Ajustes grade

### ISSUE THREAD

**Issue by fabriziomello** [pgbr/www-2015#51]
Precisamos fazer os seguintes ajustes na grade:

1) Dia 20/11 - 10h
Eliminamos a palestra do Telles que foi adicionada pela desistencia de um palestrante (essa era uma das gorduras que usamos). E invertemos os outros dois palestrantes de Auditório porque o Jaime é de fora do pais.

2) Dia 20/11 - 11h
As palestras do Juliano e do Anderson colocamos no Auditorio Secundário reduzindo o tempo para 25min cada (notifico eles sobre essa mudança)

3) Dia 20/11 - 13h
Eliminamos a palestra do Álvaro Herrera. Essa é outra palestra que solicitei como adicional para termos conteúdo e creio que ele nao se importa, visto que a palestra importante como segundo keynote ele irá realizar no dia 19/11. Então ficamos com as palestras do Fernando e do Diogo (que sao assuntos bem interessantes)

4) E também precisamos inverter os Lightning Talks com o Fishbowl que está errado...

Dessa forma teremos apenas 2 (dois) auditórios. A sala será utilizada apenas para o Coach Clinic no dia 19/11 pela parte da tarde que está sendo tocado pelo @centeno e o @gelias

**Comment by sebawebber** [comment]
@fabriziomello acho que está ok. Vou comitar e tu dá uma validada.

Se estiver tudo ok, favor fechar esse issue.
