### ISSUE TITLE
Chamada de Trabalhos

### ISSUE THREAD

**Issue by fabriziomello** [pgbr/www-2015#8]
Precisamos bolar como iremos fazer a chamada de trabalhos no site. Seja com alguma ferramenta/página/doc no google.

**Comment by nbluis** [comment]
Eu gosto bastante do http://call4paperz.com/ pois ele permite a comunidade votar nas propostas.
Mas um formulario do google também resolve se a decisão for da staff.

**Comment by fabriziomello** [comment]
Criada uma página para chamada de trabalhos no call4paperz: http://call4paperz.com/events/pgbr2015-conferencia-brasileira-de-postgresql

Não vamos inventar nada então usaremos o mesmo texto que em 2013: http://pgbr.postgresql.org.br/2013/chamada.php

**Comment by fabriziomello** [comment]
Pessoal, onde estamos com isso?? De acordo com o que coloquei ali a abertura de chamada de trabalhos é amanhã 05/05/2015

**Comment by nbluis** [comment]
@fabriziomello @centeno adicionei ao site, por favor revisem.

Não entendi ao certo se precisamos ter 3 tipos de palestras (Palesta, Palestra Regular e Palestra avançada). Para mim isso caracteriza a classificação descrita na Palestra (Básico, Internediário, Avançado). Por hora mantive conforme a anterior.

Acho que podemos dar uma melhorar nas descrições também, para ficaremos mais uniformes e simples de entender.

Por favor revisem a tradução (English Version) se puderem.

**Comment by nbluis** [comment]
A esqueci de adicionar as regras para os painéis acadêmicos.
Faço isso a noite.

**Comment by fabriziomello** [comment]
Precisamos mudar a estratégia pois o call4paperz não irá nos atender. Então precisamos criar um formulário no Google Docs com os seguintes campos:

PGBR2015 - Formulário Submissão Palestras
- Nome Palestrante (obrigatório)
- Telefone Palestrante (obrigatório)
- Email Palestrante (obrigatório)
- Cidade Origem (obrigatório)
- Foto (link) (obrigatório)
- Twitter
- Facebook
- Linkedin
- Site/Blog
- Categoria (palestra, painel academico) (obrigatório)
- Nível (basico, intermediario, avancado) (obrigatório)
- Titulo (obrigatório)
- Resumo (400) (obrigatório)
- Descrição Completa (2000) (obrigatório)
- Observações (livre)

**Comment by fabriziomello** [comment]
Pessoal,

Fiz esse formulário. O que vcs acham?

https://docs.google.com/forms/d/1zBR-g3AqpX2FJIFlT4jvbMqAivBL2jV4Ei6o3RnIfgw/viewform

**Comment by nbluis** [comment]
Dá uma olhada @fabriziomello 
Agora falta apenas as regras dos paineis.

**Comment by fabriziomello** [comment]
As regras para painel academico tem em:

http://pgbr.postgresql.org.br/2013/chamada.php

**Comment by sebawebber** [comment]
Fiz a tradução (e precisa ser revisada) das regras do painel em inglês.

No evento de 2013[1] não temos a tradução do mesmo. =/

[1] http://pgbr.postgresql.org.br/2013/chamada.en.php
